on: [push]
name: Unit tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run tests
      run: go test ./...

  fuzz:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        stable: 'false'
        go-version: 1.18.0-beta1
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run fuzzing tests
      run: go test -fuzz Fuzz -fuzztime 60s ./...
